### ISSUE TITLE
logs() - The timeout parameter is only required for status "running" and "queued"

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#109]
Also, it might be nice to increase the timeout to 60 seconds for these two cases.

**Comment by flahn** [comment]
I just realized that there are different logging functions. `log_job` does access the log once, respectively `log_service`. That is basically the direct realization of the API endpoint. `logs` on the other hand, iteratively calls those endpoints and collects updates until a timeout is reached.

I mean it is clear that timeout just refers to the `logs` function. But maybe we also need to keep in mind to visualize the outputs of `log_job` and `log_service`.

**Comment by m-mohr** [comment]
Yes, I also realized this later. Anyway, for the HTML visualization, it's not an issue anymore, I found solutions in PR #107. But the timeout should still be context-sensitive ideally.
