### ISSUE TITLE
Message with `describe_job()` unclear

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#115]
The message coming with `describe_job()` isn't 100% clear in my opinion. 
```r
To print the process graph please coerce this object into a `Process`, e.g. as(x,"Process")
``` 
_This object_ refers in my understanding to the return of `describe_job()`. It should actually be the last process node of the process graph right?

![image](https://user-images.githubusercontent.com/51962348/155166301-4473eac7-c9dd-4e8a-acfb-993954224b6f.png)

From the message I would naively try
```r
dsc = describe_job(job = job)
as(dsc, "Process")
```
It gives
```r
Error in as(dsc, "Process") : 
  no method or default for coercing “Job” to “Process”
```

**Comment by flahn** [comment]
I can confirm, the job to process coercion is currently missing, but should be an easy fix.
