### ISSUE TITLE
Documentation feedback from a user

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#126]
> > For some functions the documentation for the R-client is patchy/outdated":
> 
> The documentation that was outdated mostly referred to everything surrounding authentication. As of when I checked today, the code in the R Documentation seems to have been mostly updated, however, the surrounding text does not mention the Device Code method. Also from our experience using client-ID and secret does no longer work at the moment, and from what we heard at the LPS the plan is to retire this method entirely. Still it is described as backup method in case the simple login() does not work.
> [...]
>  As for patchy documentation, a lot of the documentation available is not specifically tailored to R. The only specific R examples (that we know of at least) are the cookbook snippets and the getting started guide, which cover a lot, but not everything.
>
> And sometimes translating from the examples given in the process list (https://openeo.org/documentation/1.0/processes.html) is not very straightforward. This was for example the case for property filters, which now was simplified a lot. Here again the documentation was updated, but the update was not immediately obvious in the documentation. (There it now mentions ?Metadata_filter, which when run in R gives a small example, which is easily overlooked)
>
> >  "Some functions are rather cumbersome to use; maybe could be simplified? e.g. cropping"
> 
> Our first example here again was the property filter, which was already improved shortly before the LPS. Another example would be cropping using filter_spatial() and mask_polygon(). As discussed on the forum (https://discuss.eodc.eu/t/cropping-with-filter-spatial/175), it is rather cumbersome to first manipulate the geoJSON string (which was also not mentioned in the documentation), then reproject the cube to WGS-84, then filter and mask and then go back to the desired projection. As for the desired outcome, in the end, the function does what it is supposed to do. Simplifying the geoJSON input might make the use more intuitive, also if the documentation mentioned what the JSON string should include and that the cube needs to be in WGS-84 it would probably already help most people.

**Comment by flahn** [comment]
As action points I read the following:
* check documentation for authentication, make it clear that basic auth and the client-id / secret part is going to be deprecated
* check posibilities for translating functions from sf (e.g. st_crop) and dplyr (e.g. filter)
* use spatial objects from sf instead of raw geoJSON (or list objects) --> this had already been implemented some weeks back

**Comment by m-mohr** [comment]
> * check documentation for authentication, make it clear that basic auth and the client-id / secret part is going to be deprecated

Only in openEO Platform, so this is nothing we need to solve in the R client in general. If at all, we need to update it on docs.openeo.cloud.
