### ISSUE TITLE
Autocompletion improvements?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#127]
If I use autocompletion/documentation features in R Studio for the core functions like describe_collection or so I get to see something like that:

![image](https://user-images.githubusercontent.com/8262166/180439670-6bf3e906-0004-4a71-82b3-d86650c7bc1e.png)

If I do the same for processes I "only" get the following:

![image](https://user-images.githubusercontent.com/8262166/180439793-0a37eaf5-c607-4a9f-8fb3-5043d144243b.png)

Is there a way to also add the right part where it shows the signature, parameters, and a summary of the process?

**Comment by przell** [comment]
@m-mohr, concerning your second screenshot if you open the brackets of the process and hit tab you should get the arguments. That's already very helpful.
To get the same layout as for "real" R functions (screenshot above), I'm doubtful that if will work with reasonable effort. @flahn?

**Comment by m-mohr** [comment]
I know, I forgot to mention that I'm just passing along feedback from the user consultation event. Thanks anyway. :-)

**Comment by m-mohr** [comment]
Maybe a bit crazy, but could we generate such .Rd documentation for processes (on demand per back-end)?

**Comment by flahn** [comment]
Unfortunately we can't to my knowledge. We might be able to create such files, but it needs to be integrated into the core package description files. We would need then to integrate the links to the files in the package description, reload the package and of course this changes for each connected back-end. 

In short I won't mess with R package integrities. Probably most OS won't allow this either.

**Comment by m-mohr** [comment]
Okay, so the only thing we could do is to e.g. make a specific version for openEO Platform but this is out of scope (for now). Thanks.
