### ISSUE TITLE
problems logging in on openeo.cloud

### ISSUE THREAD

**Issue by edzer** [Open-EO/openeo-r-client#128]
I get pretty consistently the message
```
subscript out of bounds
```
after trying to login by
```r
library(openeo)
con = openeo::connect("https://openeo.cloud")
login()
```
and later on authentication errors. I'm not sure whether this is a problem with this client, but the error (?) message is not helpful. Any ideas?

**Comment by m-mohr** [comment]
There was an issue recently on openeo.cloud where no authentication provider was exposed. I assume that's the error and the R client had an issue with getting an empty list. It should work again, right? So I'd assume the only bug here is to give a better error message or handle it differently if no authentication provider is available.

**Comment by m-mohr** [comment]
I assume this part in `login` is the issue:
```r
            providers = list_oidc_providers()
            provider = providers[[1]]
            if (is_null(provider)) {
```

We should probably check the length of providers and if it's 0, give a message that the user is required to specify a provider. Otherwise, handle it as usual...
