### ISSUE TITLE
stuck on "queued"

### ISSUE THREAD

**Issue by hurielreichel** [Open-EO/openeo-r-client#136]
running time from queued process has been very slow for me, actually, they almost stay forever as "queued" and nothing else happens. Has anyone been suffering from this?

**Comment by flahn** [comment]
Does this occur also when you use the webeditor? But from my experience it takes some time until it gets scheduled.

**Comment by m-mohr** [comment]
Vito seems very slow right now, I've seen reports on the Platform forum for jobs that have been queued for around 7 hours... so doesn't look like an R issue.
