### ISSUE TITLE
Copy xxxx-yyyy and paste when requested by the browser

### ISSUE THREAD

**Issue by edzer** [Open-EO/openeo-r-client#138]
With 1.3-0, after connecting to https://openeo.cloud, I still see
```r
> login() 
→ Copy EYMI-MCLU and paste when requested by the browser
Press <enter> to proceed:
```
but the browser never requests this code. Can the `Copy ...` sentence be omitted, or are there cases where the browser will request this code?

**Comment by m-mohr** [comment]
This is meant to give you a chance to see the instructions :-)

**Comment by m-mohr** [comment]
More weirdly though, my browser doesn't open anymore in RStudio when pressing enter.
