### ISSUE TITLE
Problem with Loading Collections

### ISSUE THREAD

**Issue by zzznelsonsm** [Open-EO/openeo-r-client#153]
I continue to get this error message: 

**No or invalid collection id(s)**

In my code, it seems like I am following the documentation.

connection = connect(host = "https://openeo.dataspace.copernicus.eu")
login()

# list collection and processes
coll = list_collections()
coll
list_processes()
p = processes()
f = list_file_formats()

collection_viewer(x="SENTINEL2_L2A")

Thank you kindly for any help!!!!

**Comment by m-mohr** [comment]
Correct, this is a bug. Please consult #154 for details and a potential solution.
