### ISSUE TITLE
User Defined functions

### ISSUE THREAD

**Issue by zzznelsonsm** [Open-EO/openeo-r-client#157]
I am trying to create a user defined function for soil adjusted vegetation index. Any help on this code? THANKS!

savi_function = function(x,context) {
  B08 = data[7]
  B04 = data[3]
  B02 = data[1]
  B03= data[2]
  1.5*(B08-B03)/(B08+ + B04 +.5)}

savi_function
  
savi_process = create_user_process(savi_function,id = "savi")
savi_process

**Comment by m-mohr** [comment]
What's the error you are encountering? Which backend are you using? Please post a fully reproducible code example.

Closing until we receive further information.
