### ISSUE TITLE
slightly complicated calculation

### ISSUE THREAD

**Issue by GISBOUKENSHA** [Open-EO/openeo-r-client#158]
Hello community,
I am beginner at programming and this package, but I have to solve slightly complicated problem. I want to apply calculation of NDVI, then when I create NDVI as raster datacube, I want to make time series only for certain pixels(which I have defined as multipoint in different coordinate system than wgs as shapefile .shp) and group and subset those pixels into separate datacubes. Then I want to filter cloud coverage of those pixels(CLM<0.2). I guess that this far it is very simple and I can manage very easily.

At this point it can be in reduce_dimension() form.

Then I want to apply function on each of those subsetted group of pixels which iterates over every pixel including those which aren't subsetted using equation in which I have to find 2% and 98% tail NDVI value of each raster and then it is stored as new band variable(for which I guess I have to use reduce_dimension() ). So as result there should be multiple raster datacubes.

I use R VITO service and sentinel2 satellite. 

I just want to hear, if it is possible or not within openeo VITO service. I already have created netCDF  rasterdatacube for desired timeline and aoi. But now I think about, what will be faster, if I should do it in a way mentioned above or just be happy, that it works and play with netCDF only.
Thank you very much.
Best regards.

**Comment by m-mohr** [comment]
I think you need to get in touch with VITO's service, this doesn't seem to be an R specific problem. The R client would support it if the VITO service is supporting it.
