### ISSUE TITLE
CLMS COPERNICUS_VEGETATION_PHENOLOGY_PRODUCTIVITY_10M_SEASON1 not correctly downloaded

### ISSUE THREAD

**Issue by andreattad** [Open-EO/openeo-r-client#159]
Thank you for the amazing work. 
I read https://documentation.dataspace.copernicus.eu/APIs/openEO/R_Client/R.html and I'm trying to download 
COPERNICUS_VEGETATION_PHENOLOGY_PRODUCTIVITY_10M_SEASON1  from connection https://openeo.dataspace.copernicus.eu, but the result are not reasonable, **probably because of erroneous georeferencing (?)** 
Only this collection has this problem, whereas COPERNICUS_VEGETATION_INDICES works perfectly. 

**Example code:**
```{r}
library(openeo)
library(terra)
library(sf)

connection = connect(host = "https://openeo.dataspace.copernicus.eu")
login()

p = processes()
collections = list_collections()
formats = list_file_formats()

data = p$load_collection(id = collections$COPERNICUS_VEGETATION_PHENOLOGY_PRODUCTIVITY_10M_SEASON1,
                         spatial_extent=st_bbox(c(xmin=11.092319,
                                   xmax= 11.132671,
                                   ymin=46.040897,
                                   ymax= 46.057888),
                                 crs = 4326),
                         bands=list("SOSD"),
                         temporal_extent = list("2020-01-01", "2020-01-01"))

result = p$save_result(data=data,format=formats$output$GTiff)
file = compute_result(graph = result, output_file = "example.tif")

r<-rast( "example.tif")
plot(r)
```

The obtained SOSD map:
![image](https://github.com/user-attachments/assets/f2bda3ff-cb78-413b-9c21-71ab945b3b2e)

VS. the obtained NDVI map:

![image](https://github.com/user-attachments/assets/c8dcf74d-32d5-487e-9a36-8a095bcbe8ba)

I checked that on the [CLMS ](https://land.copernicus.eu/en/map-viewer) the same spatial and temporal extents have reasonable result (the river can be seen).
![image](https://github.com/user-attachments/assets/6e839f35-5085-47be-abe3-ce4ebeade8a1)

**Comment by m-mohr** [comment]
This doesn't look like a client issue, I think you should contact the CDSE support instead. I can't help you with this, sorry.
