### ISSUE TITLE
Update example scripts

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#16]
We have script and Jupyter examples, but they are still in API v0.0.1. It should be updated to v0.0.2, probably (though it also depends on which backends support that...).

How should we structure them? The Python client has one notebook/example per use case, that might make things more simple. I guess we could have one per use case, with different back-ends for each to demonstrate that it works on different backends, plus one for the generic functions for listing processes, collections, etc.?

Also, it's a bit of duplication between the Jupyter and plain text examples. At the same time, they serve a bit different purposes: the text examples can be run as-is in a regular R session, whereas Jupyter is good for users to learn how to use it step by step.

**Comment by flahn** [comment]
I can provide you with the code for use case 1 that I tested this morning. I didn't add the URL for the euracHost on purpose. 

```R
library(openeo)
euracHost = ...
eurac = connect(host = euracHost,disable_auth = TRUE)
# eurac %>% listProcesses()
eurac %>% capabilities()
str(eurac %>% formats())

eurac %>% listCollections()

str(eurac %>% describeCollection("S2_L2A_T32TPS_20M"))
str(eurac %>% describeProcess("filter_bbox"))
str(eurac %>% describeProcess("filter_daterange"))
str(eurac %>% describeProcess("NDVI"))
str(eurac %>% describeProcess("min_time"))

task = collection("S2_L2A_T32TPS_20M") %>% 
  process("filter_bbox", prior.name = "imagery", left=652000,right=672000,bottom=5181000,top=5161000,srs="EPSG:32632") %>% 
  process("filter_daterange", prior.name="imagery", from= "2017-01-01", to="2017-01-31" ) %>% 
  process("NDVI", prior.name = "imagery", red="B04",nir="B8A") %>% 
  process("min_time",prior.name="imagery")

taskToJSON(task)

raster = eurac %>% executeTask(task=task,
                    format="tiff",
                    output_file = "eurac_test.tif")
job_id = eurac %>% defineJob(task=task,format="tiff")
str(eurac %>% describeJob(job_id))

list = eurac %>% downloadJob(job_id = job_id,format="tiff")

writeBin(list,"test2.tif")
str(eurac %>% describeJob(job_id))
```
