### ISSUE TITLE
HTTP 500 Internal Server Error. • SERVER-ERROR: Server error: Exception('Datatype unknown.')

### ISSUE THREAD

**Issue by surufru** [Open-EO/openeo-r-client#160]
Dear all,

I'm using openeo package to collect satellite images fro Sentinell2_L1C and it works untill i arrive to start_job function that give me back the message "HTTP 500 Internal Server Error. • SERVER-ERROR: Server error: Exception('Datatype unknown.')". 

I tried to simplify the datacube, 
I eliminated the median calculation process, 
I also try to transform the job in a proces but in this case the message change returning "HTTP 404 Not Found.
• SERVER-ERROR: The batch job '<environment>' does not exist."

I can't solve the problem, is there anyone who can give me some advice?

thanks all 

regards

P.s. below you can find the code used code.

library(openeo)
library(sf)
mask <- read_sf("D:/Progetti/SSF_INLA/shp/Mask_salerno.shp")
mask1 <- st_transform(mask, crs = 4326)
extent <- st_bbox(mask1)
connection <- connect(host = "https://openeo.dataspace.copernicus.eu")
processes <- list_processes()
login()
p <- processes()
datacube <- p$load_collection(
  id = "SENTINEL2_L1C",
  spatial_extent = list(west = extent[1] , south = extent[2], east = extent[3], north = extent[4]),
  temporal_extent = c('2024-06-01','2024-06-30'),
  bands = c("B02", "B03", "B04", "B05", "B08"),
  properties = list("eo:cloud_cover" = function(x) x <= 5)
  )
datacubeMedian <- p$median(data = datacube, ignore_nodata = T) 
formats <- list_file_formats()
result <- p$save_result(data = datacubeMedian, format = formats$output$GTiff)
job <- create_job(graph = result, title = "Draft")

######## Here is the problem ##################################################

start_job(job = job)

job1 <- as(job,"Process")
start_job(job = job1)

**Comment by m-mohr** [comment]
Hi, 
this doesn't look like an R client issue. Please ask the CDSE support for help, they'll likely better know what the issue is.
