### ISSUE TITLE
help: i can't run executeTask

### ISSUE THREAD

**Issue by ibarraespinosa** [Open-EO/openeo-r-client#18]
I'm a posdoc in atmospheric sciences from the University of São Paulo. I was trying to run the examples. I can do everything fine, but i'm getting errors in executeTask:

```
library(openeo)
conn = connect(host="http://saocompute.eurac.edu/openEO_WCPS_Driver/openeo",
               disable_auth = T, rbackend = TRUE)
conn$is_rserver = TRUE
conn %>% listCapabilities()
str(conn %>% listFormats())
conn %>% listCollections() # s2a_prd_msil1c
str(describeCollection(con = conn,
 collection_id = "s1a_t117_epsg3035_20m_VV")
)
conn %>% listProcesses()
str(conn %>% describeProcess("filter_daterange"))
str(conn %>% describeProcess("max_time"))
str(conn %>% describeProcess("filter_bbox"))
str(conn %>% describeProcess("NDVI"))
str(conn %>% describeProcess("min_time"))


task = collection("s1a_t117_epsg3035_20m_VV") %>%
  process("filter_bbox", prior.name = "imagery",
          left = 652000, right = 672000, 
          bottom = 5181000, top = 5161000,
          srs = "EPSG:32632") %>%
  process("filter_daterange", prior.name = "imagery",
          from = "2017-01-01", to = "2017-01-31") %>%
  process("NDVI", prior.name = "imagery", red = "B04", nir = "B8A") %>%
  process("min_time", prior.name = "imagery")

taskToJSON(task)
job_id = conn %>% defineJob(task)
No encoding supplied: defaulting to UTF-8.
Error in private$POST(endpoint = endpoint, authorized = TRUE, data = job) : 
  An error occured while performing an SQL-query: Unable to run insert stmt on object class JobFull {
    jobId: 1dba775d-533c-4ee7-817e-e877655ea289
    status: submitted
    processGraph: {process_id=min_time, args={imagery={process_id=NDVI, args={imagery={process_id=filter_daterange, args={imagery={process_id=filter_bbox, args={imagery={collection_id=s1a_t117_epsg3035_20m_VV}, left=652000, right=672000, bottom=5181000, top=5161000, srs=EPSG:32632}}, from=2017-01-01, to=2017-01-31}}, red=B04, nir=B8A}}}}
    output: {format={}}
    submitted: 18 Apr 2018 13:20:48 GMT
    updated: null
    userId: null
    consumedCredits: null
}: INSERT INTO `jobs` (`jobId` ,`status` ,`processGraph` ,`output` ,`submitted` ,`updated` ,`userId` ,`consumedCredits` ) VALUES (?,?,?,?,?,?,?,?)

conn %>% downloadJob(job_id)

file = conn %>% executeTask(task = task,
                            format = "tiff",
                            output_file = "test.tiff")
No encoding supplied: defaulting to UTF-8.
Error in private$POST(endpoint, authorized = TRUE, data = job, encodeType = "json",  : 
  An error occured when retrieving query result from WCPS endpoint: http://10.8.246.64:8080/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&QUERY=for%20%24c1%20in%20%28%20s1a_t117_epsg3035_20m_VV%20%29%20return%20encode%20%28%20condense%20min%20over%20%24pm%20t%20%28imageCrsDomain%28%24c1%5BDATE%28%222017-01-01%22%3A%222017-01-31%22%29%5D%2CDATE%29%29%20using%20%28%28double%29%24c1.B8A%5BE%28652000%3A672000%29%2CN%285161000%3A5181000%29%2CDATE%28%24pm%29%5D%20-%20%24c1.B04%5BE%28652000%3A672000%29%2CN%285161000%3A5181000%29%2CDATE%28%24pm%29%5D%29%20%2F%20%28%28double%29%24c1.B8A%5BE%28652000%3A672000%29%2CN%285161000%3A5181000%29%2CDATE%28%24pm%29%5D%20%2B%20%24c1.B04%5BE%28652000%3A672000%29%2CN%285161000%3A5181000%29%2CDATE%28%24pm%29%5D%29%2C%20%22tiff%22%20%29

```

I'm running in Rstudio with the following configuration:

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.10

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openeo_0.2.0      rgdal_1.2-18      raster_2.6-7      sp_1.2-7          gdalUtils_2.0.1.7
[6] jsonlite_1.5      magrittr_1.5     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      units_0.5-1       lattice_0.20-35   R6_2.2.2          foreach_1.4.4    
 [6] udunits2_0.13     stringr_1.3.0     httr_1.3.1        tools_3.4.2       grid_3.4.2       
[11] R.oo_1.21.0       e1071_1.6-8       DBI_0.8           iterators_1.0.9   class_7.3-14     
[16] yaml_2.1.18       sf_0.6-2          R.utils_2.6.0     codetools_0.2-15  curl_3.1         
[21] stringi_1.1.6     compiler_3.4.2    R.methodsS3_1.7.1 classInt_0.1-24   lubridate_1.7.4  

```
Thanks

**Comment by flahn** [comment]
It seems that the R code is OK that you submitted. However, the host you have specified is no R backend, therefore you should not use `rbackend = TRUE` in the connect statement and also not `conn$is_rserver = TRUE`. If this is somewhere in the examples, then meaculpa and I will fix that by time.

But now to the problem at hand. There are two issues here. First, those errors you mentioned I can reproduce, but they are not errors in the client. The host you stated is one of our project partners and it seems there are some issues with it (the openEO project is at an early stage of development and many things change in a short period). I will send him a mail. Second the collection you stated **s1a_t117_epsg3035_20m_VV** only has 1 band which will crash in the NDVI calculation at latest. See `str(conn %>% describeCollection("s1a_t117_epsg3035_20m_VV"))` for reference. In our test cases we usually used the Sentinel 2 scene (S2_L2A_T32TPS_20M) which will have the correct bands for calculating the NDVI.

**Comment by ibarraespinosa** [comment]
Dear @flahn,

Thanks for your quick message. 

I perceived that the time range goes from 2014-10-13 17:06:58 to 2016-09-20 17:07:09

> str(describeCollection(con = conn,
+  collection_id = "s1a_t117_epsg3035_20m_VV")
+ )
List of 1
 $ :List of 5
  ..$ extent    :Formal class 'Extent' [package "raster"] with 4 slots
  .. .. ..@ xmin: int 4217020
  .. .. ..@ xmax: int 4614160
  .. .. ..@ ymin: int 2439080
  .. .. ..@ ymax: int 2786800
  ..$ product_id: chr "s1a_t117_epsg3035_20m_VV"
  ..$ time      :List of 2
  .. ..$ from: POSIXct[1:1], format: "2014-10-13 17:06:58"
  .. ..$ to  : POSIXct[1:1], format: "2016-09-20 17:07:09"
  ..$ bands     :List of 1
  .. ..$ :List of 1
  .. .. ..$ band_id: chr "VV"
  ..$ crs       :Formal class 'CRS' [package "sp"] with 1 slot
  .. .. ..@ projargs: chr "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

Then, to avoid any problem with raster with only one band I tried:

library(openeo)
conn = connect(host="http://saocompute.eurac.edu/openEO_WCPS_Driver/openeo",
               disable_auth = T)
task = collection("s1a_t117_epsg3035_20m_VV") %>%
  process("filter_bbox", prior.name = "imagery",
          left = 652000, right = 672000, 
          bottom = 5181000, top = 5161000,
          srs = "EPSG:32632")


> job_id = conn %>% defineJob(task) No encoding supplied: defaulting to UTF-8. Error in private$POST(endpoint = endpoint, authorized = TRUE, data = job) :    An error occured while performing an SQL-query: Unable to run insert stmt on object class JobFull {     jobId: 6b688417-291f-4e64-9800-6fde4f3544e3     status: submitted     processGraph: {process_id=filter_bbox, args={imagery={collection_id=s1a_t117_epsg3035_20m_VV}, left=652000, right=672000, bottom=5181000, top=5161000, srs=EPSG:32632}}     output: {format={}}     submitted: 18 Apr 2018 14:09:29 GMT     updated: null     userId: null     consumedCredits: null }: INSERT INTO `jobs` (`jobId` ,`status` ,`processGraph` ,`output` ,`submitted` ,`updated` ,`userId` ,`consumedCredits` ) VALUES (?,?,?,?,?,?,?,?)

> file = conn %>% executeTask(task = task,
+                             format = "tiff",
+                             output_file = "test.tiff")
No encoding supplied: defaulting to UTF-8.
Error in private$POST(endpoint, authorized = TRUE, data = job, encodeType = "json",  : 
  An error occured when retrieving query result from WCPS endpoint: http://10.8.246.64:8080/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=ProcessCoverages&QUERY=for%20%24c1%20in%20%28%20s1a_t117_epsg3035_20m_VV%20%29%20return%20encode%20%28%20%24c1%5BE%28652000%3A672000%29%2CN%285161000%3A5181000%29%5D%2C%20%22tiff%22%20%29

without sucess. Hence, perhaps kthe problem is on the server side.

**Comment by flahn** [comment]
Since the creation of this post the API changed significantly and so did the R client. The issue had gone stale, so I will close it for now. If similar issues arise, please feel free to reopen the issue or create a new one.
