### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#20]
Sometimes the R client returns error messages that are not very helpful, mostly reporting an error in the sending function (POST, GET, ...). For example, running the third task of the hackathon without max_time process leads to:
```
No encoding supplied: defaulting to UTF-8.
Error in private$POST(endpoint, authorized = TRUE, data = job, encodeType = "json",  : 
```
With the old API version 0.0.2 it's for sure not to easy to return something meaningful, but for the next version we should make sure that no such message as the one above can appear. But also with the old version it would better to say what problem occurred in POST, e.g. received HTTP code 400 or whatever.

**Comment by flahn** [comment]
Usually there are error messages provided, as the colon at the end indicates. There is either nothing returned from the server or the response is either not a JSON response and/or has no attribute "message". But yes, we should improve this mostly cryptic errors.

**Comment by m-mohr** [comment]
Indeed, there is no error message returns. For now, I'd completely remove the reference to private$POST and return something more informative depending on the HTTP status code (400 = Invalid request, 403, Unauthorized, 404 = Not found and so on). But this will probably be sorted out anyway with API version 0.3 as error handling got a rework.

**Comment by GreatEmerald** [comment]
A fun example using the GEE backend, using this snippet:
```
pgb$filter_daterange(from = "2014-06-01", to= "2013-09-15") %>% 
```
Gives this error:
```
No encoding supplied: defaulting to UTF-8.
Error in private$POST(endpoint, authorized = TRUE, data = job, encodeType = "json",  : 
  {}
Error in private$POST(endpoint, authorized = TRUE, data = job, encodeType = "json",  : 
  {}
```

**Comment by GreatEmerald** [comment]
Another example: what happens when authentication expires. Doing anything that requires authentication gives an empty error:
```
> listFiles(con)
Error in private$GET(endpoint, TRUE, type = "application/json") : 
> con %>% uploadUserData(content="polygon.json",target="polygon.json")
No encoding supplied: defaulting to UTF-8.
Error in private$PUT(endpoint = endpoint, authorized = TRUE, data = upload_file(file.path,  : 
  
Error in private$PUT(endpoint = endpoint, authorized = TRUE, data = upload_file(file.path,  : 
  
```

**Comment by flahn** [comment]
To see the original server request / responses switch on `debug()`. Apart from that since API 0.3.0 we got an improved error description from the back-ends.
