### ISSUE TITLE
Making required packages optional

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#21]
It would be useful to look over the packages that the client requires and see if they can be made optional (quite like the `raster` package suggests, rather than requires, `rgdal`). At this point, it is really heavy on dependencies, and they even require installing external packages (udunits2 from `sf` and cairo for some other dependency are the main concerns). In some cases, if the user doesn't have root access, installing packages with external package dependencies may be outright impossible, so making those requirements optional would help usability a lot.

**Comment by flahn** [comment]
Regarding `raster` and gdal related packages, there were changes while working on #22

**Comment by flahn** [comment]
As far as I can see it, then `sf` is not required by the client package.

**Comment by GreatEmerald** [comment]
Right now also the entirety of dplyr is being pulled in, also with heavy dependencies. Also, what is `sp` used for here?

**Comment by flahn** [comment]
The sp package is used when you want to visualize a collection with mapView. In prior versions of the client the sp package was used to resolve the EPSG code and to create a SpatialPolygon object of the collection extents. `sp` might be shifted to suggestions.

`dplyr` on the other hand is heavily used. For example the available endpoints of a back-end are stored in a tibble and by using dplyr the filtering is done. I can't exactly tell if I use it in other places also, if not I will consider removing the dependency and doing the filtering differently.

**Comment by GreatEmerald** [comment]
Yea, best if you do that with `sf` in suggestions instead.

I noticed that sometimes a tibble is returned, but it's just a simplified data.frame, and you also have a dependency on `tibble` as well as `dplyr`, which seems like a bit too much.

**Comment by flahn** [comment]
In the last weeks I got rid off the large dependencies. But if tibble is available and loaded, tables are printed nicer.
