### ISSUE TITLE
Job workflow handling

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#26]
Right now all job-related functions seem to take the job ID. While that can be extracted from `listJobs()`, it's not what you want the users to be manually doing. So maybe have `listJobs()` be an actual list of `Job` objects that can then be passed to the other functions instead of the job ID?

**Comment by flahn** [comment]
just as a note: the "jobs" obtained from the list are only overview objects. However I changed multilple functions to allow the job object as argument. Maybe I will also look into it, if it makes sense to allow the small job objects from the list.
