### ISSUE TITLE
EURAC uc1 example for R Client is giving an error

### ISSUE THREAD

**Issue by prateekbudhwar** [Open-EO/openeo-r-client#28]
In the example code " eurac-uc1-example.R " the line " job_id = eurac %>% defineJob(task=task,format="tiff") " is giving an error related to JSONexception. I also tried to run using format=GTiff , but still the same error.

**Comment by flahn** [comment]
which project branch did you use and which API version does your back-end support?

**Comment by prateekbudhwar** [comment]
I used the master branch of R client and our EURAC backend is supporting v0.3.1

**Comment by flahn** [comment]
is this still an open issue? If so, can you also post the JSON that you have used as `task`?

**Comment by prateekbudhwar** [comment]
Here is the task used,

pgb = eurac %>% pgb()

task = pgb$collection$S2_L2A_T32TPS_20M %>%
  pgb$filter_bbox(extent=list(west=10.99,east=11.25,south=46.59,north=46.76)) %>%
  pgb$filter_daterange(extent = c("2016-01-01T00:00:00Z", "2016-03-10T23:59:59Z")) %>%
  pgb$NDVI(red="B04",nir="B8A") %>%
  pgb$min_time() %>%
  pgb$stretch_colors(min = -1, max = 1)

**Comment by flahn** [comment]
as it seemed there was an issue on the client that transformed the process graph into a json object, but as a String. I fixed this and put it into the development branch. You might install the R client from the branch `develop`. You can do it  by `install_github(repo="Open-EO/openeo-r-client",ref="develop",dependencies=TRUE)`. If it works I will push the changes also in the `master` branch.

This will fix the issue on the client side. However, there seems to be an issue on the back-end if I want to store the job. You might use `debug()` and `debug.off()` to toggle the debugging mode, which shows you the used HTTP request and response.

**Comment by prateekbudhwar** [comment]
we tested it now with develop branch, but gives another error as below, task used is the same still,

job_id = eurac %>% defineJob(task=task,format="GTiff")
lexical error: invalid char in json text.
                                       An error occured while performi
                     (right here) ------^
