### ISSUE TITLE
Error: Cannot access data endpoint

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-r-client#4]
I'm trying to update the Jupyter Notebook example to API v0.0.2, and somehow it seems that all communications with the local R backend fail with this error:

```
Error in private$GET(endpoint, type = "application/json"): Cannot access data endpoint
Traceback:

1. listProcesses(conn)
2. .listToDataFrame(con$listProcesses())
3. con$listProcesses()
4. private$GET(endpoint, type = "application/json")
5. stop("Cannot access data endpoint")
```

I'm not sure if this is an issue with the client or with the server. `connect()` seems to succeed, though:
```
Registered 'http://localhost:8000/api' as host
Login successful.
```
And I can access the `__swagger__` page through the browser fine, too.

I'm using the devel branch versions of both packages.

**Comment by flahn** [comment]
Wrapped the akward setting of the R6 attributes to be part of the `connect` call.

```R
con = connect(host = "http://localhost:8000/api/",user = "test",password = "test",rbackend=TRUE)
```

**Comment by GreatEmerald** [comment]
That works, thanks!

Then this issue can be closed here, given that this is an issue in the backend and not the client.
