### ISSUE TITLE
CRAN? 

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#41]
I'm updating the homepage and wondering whether there's an official CRAN release? If not we should consider one for 0.4 or the latest for 1.0

**Comment by flahn** [comment]
It is planned to release it on CRAN at some point. We need to tackle the usability issues first, e.g. the mechanics how to create a process graph with respect to the R users habits. Then we can make an official CRAN release.

**Comment by flahn** [comment]
today the package got accepted at CRAN
