### ISSUE TITLE
Connect to highest available api_version as default

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-client#44]
> > ```r
> > con = connect(host = gee_host_url, version="0.4.2", user = user, password = pwd, login_type = "basic")
> > ```
> > 
> > 
> > Why do I have to set the version? 0.4.2 is the "default" for GEE and should be discovered through the well known discovery mechanism.
> 
> Yes, you are right. I have to look at this.
> 

I'm not sure, but I could find anything about a default implementation - neither in the 0.4.2 nor 1.0.0 API. There is something about "production" readiness, but apart from that there is nothing. 

In the R client this is currently handled in the following ways:
1. if you pass a direct link (where capabilities are called) as host you don't need a version
2. if you have the link to the well-known doc you may pass a version, then the direct link is read from the document
3. you don't pass a version in 2., then you will get an overview printed about the available versions

_Originally posted by @flahn in https://github.com/Open-EO/openeo-r-client/issues/43#issuecomment-580740765_

**Comment by flahn** [comment]
see https://github.com/Open-EO/openeo-r-client/issues/43#issuecomment-580745740 as the intended behavior

**Comment by flahn** [comment]
point 3 was not correct. `api_version()` lists the available versions. A missing version lead to an error. Now  the intended behavior is achieved

**Comment by m-mohr** [comment]
For reference, here is the JS implementation: https://github.com/Open-EO/openeo-js-commons/blob/dev/src/versions.js#L75
Here are some tests: https://github.com/Open-EO/openeo-js-commons/blob/dev/tests/versions.test.js#L67
