### ISSUE TITLE
Parameter ordering

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-client#45]
At the moment there was no real use case to bother with the parameter order. But there are some use cases where the specific order might be usefull:

1. when creating ProcessNodes using the Process graph builder functions
2. in cases were a back-end really needs the values ordered and cannot make use of named parameter

_References @m-mohr in https://github.com/Open-EO/openeo-r-client/issues/43#issuecomment-580738660_

**Comment by m-mohr** [comment]
> 2. in cases were a back-end really needs the values ordered and cannot make use of named parameter

A back-end MUST NEVER need them ordered! The issue is that you send the parameters as object and JSON objects have NO order. Therefore you can't even guarantee that the back-end reads them in the order you sent them in. So if there's really issues with back-ends that fail with different parameter orders, then the clients should not workaround that but let the back-end fix the issue.

**Comment by flahn** [comment]
As I see now, from version 0.4.2 towards 1.0.0 the attribute `parameter_order` was dropped. So this issue can be closed directly, as it cannot be realized in 1.0.0 anymore.

**Comment by m-mohr** [comment]
Sorry, this is not correct @flahn. parameter_order was dropped, but replaced with parameters being an array, which implicitly has an order. Therefore there's still a parameter order as before!

**Comment by flahn** [comment]
OK, currently I already use the implicit order. I will need to get the parameter names slightly different. I will revisit this issue, when I start adopting the changes for 1.0.0

**Comment by flahn** [comment]
Parameters will be ordered by an array. The client already iterates over the array and retain the order of the parameters. In an R function call you have either the parameter order or the named variables for parameter assignment, so this will resolve the issue about parameter ordering.
