### ISSUE TITLE
run_udf: path to udf code file fails, setwd() works

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#50]
Just a guess, but does the file exist in your workspace (`list.files()`). If you can't find the script there, then maybe adapt your workspace (`setwd()`), use an absolute path or add the folders :)

But it is more likely that I forgot the standard return of a String argument... I will fix it quickly, you can check the latest develop version tomorrow.

_Originally posted by @flahn in https://github.com/Open-EO/openeo-usecases/issues/1#issuecomment-609997186_

**Comment by flahn** [comment]
Isn't this fixed?

**Comment by flahn** [comment]
With reference to #47

**Comment by przell** [comment]
If I set the working dir to the path where the udf code .R file sits. It works.
If I use a full path to the .R udf file it throws an error.

**Comment by przell** [comment]
Setting the wd to where the BFAST_udf.R sits works. 
Using a full path to the BFAST_udf.R file produces an error. 
Here my check script:

```
library(openeo)
library(dplyr)

euracHost = "https://openeo.eurac.edu"
user = "aceo"
password = "aceo_123"
api_versions(url=euracHost)

eurac = connect(host = euracHost, 
                user = user, 
                password = password, 
                login_type = "basic")

eurac %>% describe_collection("openEO_S2_32632_10m_L2A_D22")
list_udf_runtimes(eurac)
p = processes()

setwd("/home/pzellner@eurac.edu/git_projects/openeo-usecases/WUR_BFAST_UseCase/R") # set wd to this -> works
setwd("/home/pzellner@eurac.edu") # set wd to this and use a full path doesn't work
getwd()
udfName = "/home/pzellner@eurac.edu/git_projects/openeo-usecases/WUR_BFAST_UseCase/R/BFAST_udf.R"
udfName = "/home/pzellner@eurac.edu/BFAST_udf.R"
udfName = "BFAST_udf.R"
udfCode = readChar(udfName, file.info(udfName)$size)

s2 = p$load_collection(id = p$data$openEO_S2_32632_10m_L2A_D22, 
                       spatial_extent = list(west = 11.2792, 
                                             south = 46.4643, 
                                             east = 11.4072, 
                                             north = 46.5182), 
                       temporal_extent = c("2018-06-04T00:00:00Z","2018-06-23T00:00:00Z"))

udf = p$run_udf(data = s2, udf = udfCode, runtime = 'R') #"r"
udf # this will throw an error if wd isnt set to the location where the .R UDF script sits
```

Error if wd isnt set to path where .R UDF code file sits:
```
> udf
Error in value[[3L]](cond) : 
  Error serializing parameter 'runtime' in process node 'run_udf_QKUME4259T' :cannot open the connection
In addition: Warning messages:
1: In file(con, "rb") : 'raw = FALSE' but 'R' is not a regular file
2: In file(con, "rb") : cannot open file 'R': it is a directory
```

**Comment by flahn** [comment]
It seems that the parameter "runtime" causes problems. This is a String parameter and currently I test if this is a file. I will try to catch the error and handle it.

**Comment by flahn** [comment]
doh. ok. I get similar errors. I used the r-client repository where the folder "R" exists (there are the scripts located). Now file.exists("R") is true and it is assumed that there is a script to be loaded.

**Comment by przell** [comment]
Thanks! Now the above code doesn't produce an error anymore on the r-client side!
