### ISSUE TITLE
Github examples don't work

### ISSUE THREAD

**Issue by RussellGrayxd** [Open-EO/openeo-r-client#51]
I'm new to the package and trying to test out its functionality. The eample provided by the package documentation as well as the example on the main page of the github don't work. I installed version 0.4.2 and also tried using 0.3.1

**from the documentation:**
con = connect(host='http://example.openeo.org',version='0.4.2')

Could not resolve host: example.openeo.org

**from the example on the git page**
conn = connect(host="http://backend1.openeo.org/",user="test",password="test",login_type="basic")

Could not resolve host: backend1.openeo.orgError in con$connect(url = host, version = version, exchange_token = exchange_token)$login(user = user,  : 
  attempt to apply non-function

I also can't seem to find any way outlined on the github walkthrough on how to get my own 'user' and 'password' credentials for the API. I've been searching to figure it out myself, but no luck. The documentation says (optional) so maybe this isn't necessaary anymore? 

Making things a bit clearer would help a lot!

Thanks for putting this package together, can't wait to try it out!

**Comment by flahn** [comment]
Thank you for your interest in our project and for pointing out those issues. I will update that in time.

In general the package handles the communication from your local R session to a remote server. There all computations are performed as well as all the data collections are stored there. In the openEO project we have several partners which provide different openEO services. You will need to register with one of our project partners first. Then you will get the required login credentials as well as a working URL. 

I will also edit the README accordingly, you might check out our [openEO hub](https://hub.openeo.org/) where the URLs to available back-ends are listed. I will also have a look into this cryptic error message and will improve it. The main reason why it is not working, is that the URL does not exist. I had used imaginary URLs and credentials just to showcase, how it is intended to work. For security reasons I cannot provide any valid credentials at that point.

However some partners have free-to-use access like our interface service to Google Earth Engine (see the script `/examples/GEE-examples.R`). If you want to explore the R package as well as the idea of openEO further, you have another starting point there. But keep in mind the GEE-openEO interface is intended only for demonstration purposes. You might not sign in with your own GEE account and the processing power is limited, which means that you should use only small spatio-temporal subsets and not run any calculation on full scale. 

Some more insights: The openEO project is not finished yet and there is also some further development going on. We had released the final API version some weeks ago and we are now working on updating the clients and the remote services of our partners to this new version. I apologize for any inconveniences and short-comings on documentation that come along in this transition phase and I will improve this as soon as possible.

**Comment by RussellGrayxd** [comment]
Hey again,
Thank you for the detailed information! I will have a go at the rgee example just to see how everything operates. I guess I will have to follow the project closely to stay updated on when things become a bit more stable. 
Thanks again,

-Russell Gray
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, August 18, 2020, 02:03:10 a.m. GMT+7, Florian Lahn <notifications@github.com> wrote:  
 
 


Thank you for your interest in our project and for pointing out those issues. I will update that in time.

In general the package handles the communication from your local R session to a remote server. There all computations are performed as well as all the data collections are stored there. In the openEO project we have several partners which provide different openEO services. You will need to register with one of our project partners first. Then you will get the required login credentials as well as a working URL.

I will also edit the README accordingly, you might check out our openEO hub where the URLs to available back-ends are listed. I will also have a look into this cryptic error message and will improve it. The main reason why it is not working, is that the URL does not exist. I had used imaginary URLs and credentials just to showcase, how it is intended to work. For security reasons I cannot provide any valid credentials at that point.

However some partners have free-to-use access like our interface service to Google Earth Engine (see the script /examples/GEE-examples.R). If you want to explore the R package as well as the idea of openEO further, you have another starting point there. But keep in mind the GEE-openEO interface is intended only for demonstration purposes. You might not sign in with your own GEE account and the processing power is limited, which means that you should use only small spatio-temporal subsets and not run any calculation on full scale.

Some more insights: The openEO project is not finished yet and there is also some further development going on. We had released the final API version some weeks ago and we are now working on updating the clients and the remote services of our partners to this new version. I apologize for any inconveniences and short-comings on documentation that come along in this transition phase and I will improve this as soon as possible.
