### ISSUE TITLE
Connect to latest version

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#52]
Migrated from https://github.com/Open-EO/openeo.org/pull/18:

I should be able to use `connect(host = "https://earthengine.openeo.org")` to connect to GEE according to the API spec:

> By default, a client SHOULD connect to the most recent production-ready version it supports. If not available, the most recent supported version of all versions SHOULD be connected to.

**Comment by flahn** [comment]
You can, but the `production` flag needs to be TRUE, when using `api_versions("https://earthengine.openeo.org")` on at least on version.

**Comment by m-mohr** [comment]
Users shouldn't need to care about that. By default, we should just let them connect to the back-end. If there's no production version, we fall back to non-production. That's better than to not connect ;-)

**Comment by flahn** [comment]
What is the latest version in this regard? You might have the following versions available: "1.0.0-pre-rc1", "1.0.0-rc99", "1.0.0", "1.0.0-1" (all non-productive) which one should the client choose?

Anyhow, in your definition you also stated yourself that the client should connect to the most recent *production-ready* version. That would be the case if the GEE back-end would offer a production-ready version!

**Comment by flahn** [comment]
| api_version | production | url |
|-|-|-|
| 1.0.0 | FALSE | https://earthengine.openeo.org/v1.0 |

**Comment by m-mohr** [comment]
The version numbers follow SemVer, so the newest one according to their rules. I think that is 1.0.0 in your example.

> The most recent version is determined by comparing the version numbers according to rules from Semantic Versioning, especially §11. Any pair of API versions in this list MUST NOT be equal according to Semantic Versioning.

> Anyhow, in your definition you also stated yourself that the client should connect to the most recent production-ready version.

Yes, but it continues with:

> If not available, the most recent supported version of all versions SHOULD be connected to.

**Comment by flahn** [comment]
OK. Thanks. Found an error in my code that resolves this issue completely :)

**Comment by m-mohr** [comment]
Great!
