### ISSUE TITLE
connect: Version parameter is confusing

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#57]
From D34:
> The code for connecting to the backend is straightforward by providing username and password. The version parameter is unclear, but likely useful to assure the compatibility of the code for different back-ends.

Users seem to not understand the `version` paramater in the connect method.
1. It should be clarified that this is a openEO API version implemented by the back-end, which usually doesn't need to be specified unless the user knows what he's doing.
2. Also, it's not clear where to get the version number from, a reference to api_versions() should be added.
3. The parameter should be removed from examples that don't explicitly document the parameter itself.

**Comment by flahn** [comment]
wrong reference in the commit, but I changed the mentioned point  also

**Comment by m-mohr** [comment]
Looks good, thank you!
