### ISSUE TITLE
Can't connect if server doesn't add production flag to well-known discovery (and tibble is not installed?)

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#59]
I recently was made aware of an issue with the R client:

![image](https://user-images.githubusercontent.com/8262166/102785746-bc6bb080-439e-11eb-8174-c5af667a3215.png)

I was able to track it down that the difference is:
1. the user had not installed tibble and
2. the server did not had the `production` flag in `GET /.well-known/openeo`

So I think the issue is in or around this line: https://github.com/Open-EO/openeo-r-client/blob/fccbe70cf53c3d5b4dfabeba28aac5faab04f6c0/R/coerce-functions.R#L132

I'm not sure how exactly data frames work, but it seems that it expects a `production` flag and throws an error is there's no such flag available. The flag is optional in the API, so it seems to be a bug in the R client.

Edit: Feedback from the user indicates that the issue may also exist for tibbles.

**Comment by flahn** [comment]
I stumbled onto similar issues sometimes on other occassions. It seems that sometimes the JSON message is parsed incorrect, e.g. I expect it parsed as data.frame object and it is parsed as a list. But to check this hypothesis, I would need the JSON hat is to be returned at `GET /.well-known/openeo`, can you provide it?

**Comment by flahn** [comment]
e824f6f  should fix this (referenced the wrong issue unfortunately)

**Comment by m-mohr** [comment]
I got this image:
![image](https://user-images.githubusercontent.com/8262166/102883534-77a05200-4450-11eb-9b71-fb5b098e7b5c.png)

So likely this in "text":
```
{
  "versions": [
    {
      "api_version": "1.0.0",
      "url": "http://localhost/api/v1"
    }
  ]
}
```

**Comment by flahn** [comment]
@m-mohr is this issue still open or did the mentioned commit solve  this?

**Comment by m-mohr** [comment]
Was an issue in a study project. I never tried it myself. Let's close for now, thanks.
