### ISSUE TITLE
Our Github Action fails to install devtools package

### ISSUE THREAD

**Issue by jona159** [Open-EO/openeo-r-client#60]
We are working on a [workflow](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/r-client.yml) to connect to our openEO Backend with the R-Client. Now we are facing the issue that the devtools package fails to install properly. Please have a look at our [Action](https://github.com/GeoSoftII2020-21/TestRepo/runs/1734895136?check_suite_focus=true) for further information. During our research we recognized that other people ran into the same problem, but we could not yet find a solution that works for us. Any recommendations are much appreciated!

**Comment by flahn** [comment]
It seems you haven't installed libcurl at your Linux machine. Lines 709ff. in your error log should guide you. Apart from that, if you just need the R package to install github tools, you might look at the [remotes package](https://cran.r-project.org/web/packages/remotes/index.html) instead of devtools.

**Comment by flahn** [comment]
Meaning something like `apt-get install libcurl4-openssl-dev` for Ubuntu. In any case to communicate with webserver in general you would often times need [curl](https://wiki.ubuntuusers.de/cURL/)

**Comment by jona159** [comment]
Thanks a lot! I adjusted the [workflow](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/r-client.yml) and i think we made some progress. However now we run into this Error: 
![connect_function_error](https://user-images.githubusercontent.com/65068389/105241397-e830b080-5b6d-11eb-92eb-69ab00e9111b.png)
Do you have any advice on this as well? 
I am aware this is a seperate problem, so please consider closing this issue

**Comment by flahn** [comment]
Please load the openeo package first, before using the `connect()` function.

**Comment by jona159** [comment]
We actually do load the openeo package, i should have provided this information in the screenshot aswell: 

![connect_not_found](https://user-images.githubusercontent.com/65068389/105420731-2ea30f80-5c41-11eb-8e6e-bbea9b00c100.png)

In our yaml-file it looks like this: 

![workflow_yml](https://user-images.githubusercontent.com/65068389/105422600-48922180-5c44-11eb-9031-c3a5a3d2466c.png)

**Comment by flahn** [comment]
As far as I know, running R directly from command line / shell with an expression (`-e`) does not preserve the session. Which means that in a former call you had loaded the package and closed the R session afterwards. Imagine this, you started RStudio typed `library(openeo)` and closed the application. Then you opened run it again (with a fresh session) and run your next command. Do you see the problem?

You can either combine package loading and connecting in one expression or you reference the connect function directly.

a) `R -e 'library(openeo); gee = connect(host = "https://earthengine.openeo.org")'`
b) `R -e 'gee = openeo::connect(host = "https://earthengine.openeo.org")'`

**Comment by jona159** [comment]
I see, that was the problem, thanks a lot again!
