### ISSUE TITLE
oidc login on eurac not working

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#61]
Hi Florian, 
we have implemented open id connect authentication for our backend. It works on the webeditor.
I am trying to login via the r-client (v1.0.0) but I get a "Login failed.". I have written you an e-mail containing the conf information.
Here's what I have tried so far:
Login via `connect()` function:
```
euracHost = "https://openeo.eurac.edu"
conf = list(client_id = "xxx", secret = "xxx")

eurac = connect(host = euracHost) # connect to get oidc providers
prov = list_oidc_providers()
prov$Eurac_EDP_Keycloak

eurac = connect(host = euracHost, 
                            login_type = "OIDC", 
                            provider = prov$Eurac_EDP_Keycloak, # "Eurac_EDP_Keycloak", 
                            config = conf)
```
I get: 
```
Connected to service:  https://openeo.eurac.edu 
Please check the terms of service (terms_of_service()) and the privacy policy (privacy_policy()). By further usage of this service, you acknowledge and agree to those terms and policies.
Warning: Connected host is considered unstable and not production-ready. Unexpected errors might occur.
Login failed.
```
Login via `login()`:
```
euracHost = "https://openeo.eurac.edu"
conf = list(client_id = "xxx", secret = "xxx")

eurac = connect(host = euracHost) # connect to get oidc providers
prov = list_oidc_providers()
prov$Eurac_EDP_Keycloak

login(login_type = "oidc", provider = prov$Eurac_EDP_Keycloak, config = conf, con = eurac)
```
I get (I looked into the code authentication.R, there I see that the error "Login failed." is only thrown by the object BasicAuth, so I don't know where it goes wrong):
```
Login failed.
```

The provider object looks like this:
```
> prov$Eurac_EDP_Keycloak
$id
[1] "Eurac_EDP_Keycloak"

$issuer
[1] "https://edp-portal.eurac.edu/auth/realms/edp"

$scopes
NULL

$title
[1] "Eurac EDP Keycloak"

$description
[1] "Keycloak server linking to the eurac active directory. This service can be used with Eurac and general MS accounts"

$links
$links[[1]]
$links[[1]]$href
[1] "https://edp-portal.eurac.edu/auth"



attr(,"class")
[1] "Provider"
```

I can't identify the problem :(
When turning on the `debug()` connecting doesn't work any more like this `eurac = connect(host = euracHost)`. It gives `missing value where TRUE/FALSE neededInvalid openEO host stated. Please use an URL pointing to a valid openEO webservice implementation.`. When turning on `debug()` after the connection is established and trying `login(login_type = "oidc", provider = prov$Eurac_EDP_Keycloak, config = conf, con = eurac)` I still only get the `Login failed.` error.

Have you connected successfully to any backend using OIDC yet? 

All the best, 
Peter

**Comment by flahn** [comment]
@przell , please check if the latest develop version fixes this issue, there was indeed a problem in an "if" statement that threw an error message, when something other was passed as parameter than a path to a json file containing those secrets. I fixed that and it should not throw an error anymore.

**Comment by przell** [comment]
@flahn, thanks for the quick fix! The authentication works now on our backend using the latest dev version of the r-client!

![image](https://user-images.githubusercontent.com/51962348/110964004-038c9080-8353-11eb-8eb1-670f475a38d5.png)
