### ISSUE TITLE
Auto-completion for compute_result file extension

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#62]
| Title | Auto-completion for compute_result file extension |
| --- | --- |
| Date | 2021-05-12 |
| Issue | https://github.com/Open-EO/openeo-r-client/issues/62 |
| Category | Visualisation, Reporting |
| Description | Adjusting the correct names and short names for file extensions is teadious and a source of error, since it depends on the backend how the extension is expressed (e.g., .netcdf vs. .nc). Querrying the backend for the possible extensions and making them available via auto completion would ease the process significantly. |
| Dependencies |  |
| Links | Facilitates local prototyping |
| Priority | Medium|
| Impact | Medium |

An idea to increase usability is to auto-complete the file extension according to the format chosen in `compute_result`. This would be convenient when changing output formats so it doesn't have to be specified in 3 places. I think this is done in the python client.

```
#' load a collection
data = p$load_collection(id = ado_colls_names$ADO_NDVI_MODIS_231m_3035, 
                         spatial_extent = bbox,
                         temporal_extent = time_range)

#' check the file formats available. 
list_file_formats()

#' save the result. for a point ts json is suitable.
result = p$save_result(data = data, format="JSON") #1

#' ## compute the result -------------------------------------------------------

#' synchronous (result is computed directly)
compute_result(result,
               format = "JSON", #2
               output_file = "openeo_interactive_point.json",  #3
               con = eurac)
```

**Comment by flahn** [comment]
I'm quite certain that this feature is already implemented. Try to store the object returned from `list_file_formats()` the list should have two entries for *input* and *output*. 

See https://github.com/Open-EO/openeo-r-client/blob/master/examples/GEE-examples.Rmd caption 6 b)

**Comment by flahn** [comment]
To recap on that: The change would be adding "format" as parameter (probably allowing all parameters of the backends "save_result" in `...`) and then either add the `save_result` ProcessNode as end node or replace the values set were previously set with the ones of compute_result.

This would also benefit the sample data retrieval. When it comes to asynchronous processing I would assume the user needs to put a `save_result` explicitly.
