### ISSUE TITLE
Formatting errors in Jupyter Notebook

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-client#7]
I realized that some output is not formatted correctly. For example, when I look at the file from Pull-Request #5 via [GreatEmerald/openeo-r-client/.../notebooks/Syntax.ipynb](https://github.com/GreatEmerald/openeo-r-client/blob/61382c678dbe0d553de4b1a2d7e647bf1b9f24d6/examples/notebooks/Syntax.ipynb), then it seems that in some returns, often with processes, "_" is interpreted as subscription of letters.

**Comment by GreatEmerald** [comment]
Yes, that's the GitHub bug I was talking about. Somehow the output is misinterpreted by GitHub as being LaTeX, even though in reality it's just bolded plain text. You should look at the notebooks by opening them in Jupyter instead.
