### ISSUE TITLE
Support AuthCode (or DeviceCode) + PKCE so that the default clients can be used

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-r-client#76]
Related issues: https://github.com/r-lib/httr/issues/705 and https://github.com/r-lib/httr2/issues/92

We should look into httr2: https://httr2.r-lib.org/reference/index.html#section-authentication

No Device Code + PKCE, but AuthCode + PKCE is supported. That should make it work for us easily, but what effort is this?

**Comment by m-mohr** [comment]
This seems to work very well:

```r
> library(openeo)
> connect(host = "https://openeo.cloud")
Connected to service:  https://openeocloud.vito.be/openeo/1.0.0 
Please check the terms of service (terms_of_service()) and the privacy policy (privacy_policy()). By further usage of this service, you acknowledge and agree to those terms and policies.
Warning: Connected host is not production-ready. Unexpected errors might occur.
> login(login_type = "oidc")
Use code g8Q...
Login successful.
> describe_account()
ID:	25254c4db1930c...
Name:	m.mohr@...
```

I think we should describe the process a bit more. "Use code ..." is very short.

To align with the Python client I'd suggest something like this:

> A browser window should have been opened for authentication. Otherwise, please visit https://provider.example.com/device
> Once requested please enter the code 'DTNY-KLNX'.

**Comment by flahn** [comment]
I'm not sure, if I can change that text, because that is managed by httr2. Maybe in that particular case the changes are currently in our package, but will be merged into httr2 eventually.

**Comment by m-mohr** [comment]
Ah, it seems they try to handle it internally somehow. Not sure how reliable that is though:
https://github.com/r-lib/httr2/blob/main/R/oauth-flow-device.R#L63
Okay, fine for me until users complain ;-)

**Comment by mattia6690** [comment]
While trying the new connection methods we realized that with old versions of R the login through EGI (via Authorization Code) is not working. You connect but you cannot log in, you do not receive a code. It is working with R version 4.0.5 and 4.1.1 but not with 3.6.3. We tried the current version 1.2.0 of the development branch

**Comment by flahn** [comment]
@mattia6690 can you check again with the recent 'develop' branch?

**Comment by mattia6690** [comment]
> @mattia6690 can you check again with the recent 'develop' branch?

Now it is working also with R version 3.6.3!
