### ISSUE TITLE
Authentication with R-Studio Server running on different Server

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#77]
Currently it is not possible to authenticate when the R-Studio Server Instance is running on a different VM than the internet browser. The authentication is always redirecting to http://localhost:1410/. 
Not sure if this is a client issue or generally not yet adressed by the API.
![image](https://user-images.githubusercontent.com/51962348/136416276-ad3fcc6f-0b02-4c71-84a7-e0ba7a675b42.png)

**Comment by m-mohr** [comment]
Yes, the only solution I could see for this case is to either use Device Code Flow + PKCE (see httr2 issue) or to support two different grant types (also through httr2): AuthCode for "normal use cases" and e.g. client credentials (i.e. with a secret, so difficult for openEO Platform to manage) for RStudio Server, remote Jupyterlabs and similar cases.

**Comment by przell** [comment]
should be solved when #76 is solved

**Comment by m-mohr** [comment]
In a Jupyter environment I'm getting the following error:

> Error in value[[3L]](cond): Login failed. Reason: OAuth 2.0 device flow requires an interactive session

Isn't it exactly meant that the device code should work in such an environment?

**Comment by flahn** [comment]
Hmm, usually that should work. If the session is not interactive, then the URL and the code are printed to console. I will look into it.

**Comment by flahn** [comment]
Probably you can solve this by enabling the interactive mode in the IRKernel for Jupyter 

https://github.com/IRkernel/IRkernel/issues/236

**Comment by m-mohr** [comment]
Okay, will check. But better would be if this would not be required. Where is this originating from? HTTR2? In principle this should not appear as we have implemented PKCE so we may need to disable that in HTTR2, unfortunately.

**Comment by m-mohr** [comment]
Thrown here: https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-client.R#L223
