### ISSUE TITLE
Provide Vue Components in R markdown and Jupyter

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-r-client#91]
| Title | Provide Vue Components in R markdown and Jupyter |
| --- | --- |
| Date | 2021-11-11 |
| Issue | https://github.com/Open-EO/openeo-r-client/issues/91 |
| Category | Visualisation, Reporting |
| Description | Interactive Vue Components based on java srcipt are available in openEO. They allow interactive rendering of process graphs, collections, process descriptions, etc. They are already integrated in the python client. The integration into the R-Client unifiese the user experience accross the clients (python, webeditor, R) by reusing the same visualization tools. It is favourable to have the widgets working in RStudio Viewer, Rmarkdown and when running R in Jupyter Notebooks.  |
| Dependencies | Vue Components (https://github.com/Open-EO/openeo-vue-components), RStudio, Rmarkdown, Jupyter |
| Links | Visualization of COGs |
| Priority | High |
| Impact | High |

**Comment by przell** [comment]
This could be helpful: https://rdrr.io/cran/mapview/src/R/print.R

**Comment by m-mohr** [comment]
I've checked some docs and there seem to be different options for Jupyter and RMarkdown:

1. jupyter: https://irkernel.github.io/docs/repr/0.9/ which is using repr_html as in Python
2. jupyter: https://github.com/IRkernel/IRkernel where you can use IRdisplay::display_html
3. rmarkdown: Use htmltools::html_print and overload print as shown in https://rdrr.io/cran/mapview/src/R/print.R

To be clarified: Does one method work for all environments?

**Comment by m-mohr** [comment]
Here's some code from experiments that seems to work for jupyter and rstudio notebooks, but still has some issues in knitr (gives 'Argument hat Länge 0', not sure why, anyone can help?):

```r
        html_output = paste('<p>Connected to <a href="',private$host,'" target="_blank">',private$host,'</a></p><p><small>TODO... (env: ~env~)</small></p>', sep = '')
        if (getOption('jupyter.in_kernel') == TRUE) {
          IRdisplay::display_html(sub('~env~', 'jupyter', html_output))
        }
        else if (getOption('rstudio.notebook.executing') == TRUE) {
          print(htmltools::HTML(sub('~env~', 'rstudio', html_output)))
        }
        else if (getOption('knitr.in.progress') == TRUE && knitr::is_html_output() == TRUE) {
          htmltools::HTML(sub('~env~', 'knitr', html_output))
        }
        else {
          cat("Connected to service: ",private$host,"\n")
          cat("Please check the terms of service (terms_of_service()) and the privacy policy (privacy_policy()). By further usage of this service, you acknowledge and agree to those terms and policies.\n")

          if (!hostInfo[hostInfo$url == private$host,]$production) {
            message("Warning: Connected host is not production-ready. Unexpected errors might occur.")
          }
        }
```

Jupyter:
![image](https://user-images.githubusercontent.com/8262166/143076329-bc86db48-6180-409c-a5fd-fbbc2a4a9126.png)

RStudio NB:
![image](https://user-images.githubusercontent.com/8262166/143076400-551f72f0-74d2-44c7-8497-62750ef4a141.png)

**Comment by flahn** [comment]
I will provide a fix in a minute in a separate PR towards your ui-component branch. Maybe have a look at #110. When we are not setting an id for the UDP manually, then nothing is printed.
