### ISSUE TITLE
vignette process graph building

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-r-client#96]
| Title        | Vignette Process Graph Building                           |
| ------------ | ----------------------------------------------------------- |
| Date         | 2021-11-18                                                  |
| Issue        | [#96](https://github.com/Open-EO/openeo-r-client/issues/96) |
| Category     | Documentation                                                   |
| Description  |    There are multiple examples on how to use the openeo package - in a separate folder / the project wiki, etc. For R users the common way to look for information how to use functions provided by an R package is to look for examples in form of a vignette and also read through the function documentation. With this in mind a vignette has to be created that builds on the introductionary vignette (Getting Started) and elaborates and highlights certain functionalities in more detail.                                                        |
| Dependencies |                                                            |
| Links        |                                                             |
| Priority     |    Medium                                                         |
| Impact       |      Medium                                                       |
| Effort       |         Medium                                                    |

provide vignette for process graph building

**Comment by flahn** [comment]
With the release of version 1.3.0 several vignettes have been added that cover the concepts of the process graph building in openEO as well as an exemplary code based vignette.
